/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings */

#ifndef _Included_com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings
#define _Included_com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings
 * Method:    createCrunchyHybridDecrypterBindings
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings_createCrunchyHybridDecrypterBindings
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings
 * Method:    destroyCrunchyHybridDecrypterBindings
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings_destroyCrunchyHybridDecrypterBindings
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings
 * Method:    decrypt
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_security_crunchy_jni_CrunchyHybridDecrypterBindings_decrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
