/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_security_crunchy_jni_CrunchyCrypterBindings */

#ifndef _Included_com_google_security_crunchy_jni_CrunchyCrypterBindings
#define _Included_com_google_security_crunchy_jni_CrunchyCrypterBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_security_crunchy_jni_CrunchyCrypterBindings
 * Method:    createCrunchyCrypterBindings
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_google_security_crunchy_jni_CrunchyCrypterBindings_createCrunchyCrypterBindings
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyCrypterBindings
 * Method:    destroyCrunchyCrypterBindings
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_security_crunchy_jni_CrunchyCrypterBindings_destroyCrunchyCrypterBindings
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyCrypterBindings
 * Method:    encrypt
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_security_crunchy_jni_CrunchyCrypterBindings_encrypt__J_3B
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyCrypterBindings
 * Method:    decrypt
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_security_crunchy_jni_CrunchyCrypterBindings_decrypt__J_3B
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyCrypterBindings
 * Method:    encrypt
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_security_crunchy_jni_CrunchyCrypterBindings_encrypt__J_3B_3B
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyCrypterBindings
 * Method:    decrypt
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_security_crunchy_jni_CrunchyCrypterBindings_decrypt__J_3B_3B
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
