/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_security_crunchy_jni_CrunchyVerifierBindings */

#ifndef _Included_com_google_security_crunchy_jni_CrunchyVerifierBindings
#define _Included_com_google_security_crunchy_jni_CrunchyVerifierBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_security_crunchy_jni_CrunchyVerifierBindings
 * Method:    createCrunchyVerifierBindings
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_google_security_crunchy_jni_CrunchyVerifierBindings_createCrunchyVerifierBindings
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyVerifierBindings
 * Method:    destroyCrunchyVerifierBindings
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_security_crunchy_jni_CrunchyVerifierBindings_destroyCrunchyVerifierBindings
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyVerifierBindings
 * Method:    verify
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_google_security_crunchy_jni_CrunchyVerifierBindings_verify
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
