/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings */

#ifndef _Included_com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings
#define _Included_com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings
 * Method:    createCrunchyHybridEncrypterBindings
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings_createCrunchyHybridEncrypterBindings
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings
 * Method:    destroyCrunchyHybridEncrypterBindings
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings_destroyCrunchyHybridEncrypterBindings
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings
 * Method:    encrypt
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_security_crunchy_jni_CrunchyHybridEncrypterBindings_encrypt
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
